# Generated by Django 5.2 on 2025-05-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_payment_proof_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
