# Generated by Django 5.2 on 2025-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productobase_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobasefoto',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
