# Generated by Django 5.2 on 2025-05-25 19:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productobasefoto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobasefoto',
            name='foto',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
