# Generated by Django 5.2 on 2025-04-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categoriaproductobase'),
        ('api', '0007_order_status'),
    ]

    operations = [
    ]
