# Generated by Django 5.2 on 2025-04-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulosProductoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ManyToManyField(to='api.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_fotos')),
                ('estado', models.BooleanField(default=True)),
                ('articulos', models.ManyToManyField(blank=True, to='api.articulo')),
                ('categoriaProductoBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaproductobase')),
            ],
        ),
        migrations.CreateModel(
            name='Personalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articuloSeleccionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articulosproductobase')),
                ('categoriaArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaarticulo')),
                ('productoBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productobase')),
            ],
        ),
        migrations.AddField(
            model_name='articulosproductobase',
            name='productoBase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productobase'),
        ),
        migrations.CreateModel(
            name='ProductoBaseFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='productos_fotos')),
                ('productoBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.productobase')),
            ],
        ),
    ]
